In [1]:
println("Hola mundo!")

Hola mundo!


In [4]:
while true
    print("> ")
    linea = readline()
    if linea == "listo"
        break
    end
    println(linea)
end
println("¡Listo!")

> stdin> tolai
tolai
> stdin> tururu
tururu
> stdin> lisporra
lisporra
> stdin> listo
¡Listo!


In [5]:
# Aqui empezamos a escribir el codigo Julia compilado JIT

function foo()
    print(123)
end

precompile(foo, ()) precompila la funcion pero no la ejecuta

true

In [6]:
foo()

123

In [8]:
v = [1 3 5]

1×3 Array{Int32,2}:
 1  3  5

In [10]:
transpose(v)

3×1 LinearAlgebra.Transpose{Int32,Array{Int32,2}}:
 1
 3
 5

In [11]:
v'

3×1 LinearAlgebra.Adjoint{Int32,Array{Int32,2}}:
 1
 3
 5

In [12]:
A = [1 2 3; 4 5 6]

2×3 Array{Int32,2}:
 1  2  3
 4  5  6

In [22]:
B = [1 2 3; 4 5 6; 7 8 9]

3×3 Array{Int32,2}:
 1  2  3
 4  5  6
 7  8  9

In [23]:
zeros(3,4)

3×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [24]:
ones(3,4)

3×4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [25]:
fill(7,2,3)

2×3 Array{Int32,2}:
 7  7  7
 7  7  7

In [28]:
A = [1 2 3; 4 5 6; 7 8 9]; B =[ 3 8 4; 6 9 7; 3 9 8];

In [29]:
3.6 * A .+B -5 * A

3×3 Array{Float64,2}:
  1.6   5.2  -0.2
  0.4   2.0  -1.4
 -6.8  -2.2  -4.6

In [31]:
A .+ 10

3×3 Array{Int32,2}:
 11  12  13
 14  15  16
 17  18  19

In [34]:
-8 .-A

3×3 Array{Int32,2}:
  -9  -10  -11
 -12  -13  -14
 -15  -16  -17

In [35]:
A * B

3×3 Array{Int32,2}:
 24   53   42
 60  131   99
 96  209  156

In [36]:
B * A

3×3 Array{Int32,2}:
 63   78   93
 91  113  135
 95  115  135

In [37]:
A ^2

3×3 Array{Int32,2}:
  30   36   42
  66   81   96
 102  126  150

In [38]:
A^2 == A*A

true

In [40]:
B^(-1) * B

3×3 Array{Float64,2}:
  1.0          -8.88178e-16   0.0
 -1.94289e-16   1.0          -5.55112e-17
  0.0          -4.44089e-16   1.0

In [41]:
A^(-1)

3×3 Array{Float64,2}:
  3.15221e15  -6.30442e15   3.15221e15
 -6.30442e15   1.26088e16  -6.30442e15
  3.15221e15  -6.30442e15   3.15221e15

In [42]:
 A = [4 6 8; 7 3 1; 4 8 9]

3×3 Array{Int32,2}:
 4  6  8
 7  3  1
 4  8  9

In [47]:
inv(A)

3×3 Array{Float64,2}:
  0.256757   0.135135   -0.243243
 -0.797297   0.0540541   0.702703
  0.594595  -0.108108   -0.405405

In [48]:
A^(-1)

3×3 Array{Float64,2}:
  0.256757   0.135135   -0.243243
 -0.797297   0.0540541   0.702703
  0.594595  -0.108108   -0.405405

In [49]:
A= [1 2 3; 4 5 6; 7 8 9]
B =[3 8 4; 6 9 7; 3 9 8]

3×3 Array{Int32,2}:
 3  8  4
 6  9  7
 3  9  8

In [50]:
hcat(A, B)

3×6 Array{Int32,2}:
 1  2  3  3  8  4
 4  5  6  6  9  7
 7  8  9  3  9  8

In [51]:
[A B]

3×6 Array{Int32,2}:
 1  2  3  3  8  4
 4  5  6  6  9  7
 7  8  9  3  9  8

In [52]:
vcat(A,B)

6×3 Array{Int32,2}:
 1  2  3
 4  5  6
 7  8  9
 3  8  4
 6  9  7
 3  9  8

In [53]:
[A;B]

6×3 Array{Int32,2}:
 1  2  3
 4  5  6
 7  8  9
 3  8  4
 6  9  7
 3  9  8

In [54]:
A = [2 6; 7 9]; B = [3,7]; # Sistema compatible

In [55]:
A \ B

2-element Array{Float64,1}:
 0.625
 0.29166666666666663

In [56]:
A * ans # Comprobacion de la solucion

2-element Array{Float64,1}:
 3.0
 7.0

In [57]:
 A = [2 6; 1 3]; B = [3,7]; A \ B # Incompatible

LoadError: LinearAlgebra.SingularException(2)

In [58]:
 A = [2 6; 2 6]; B = [3, 3]; A \ B # Indeterminado

LoadError: LinearAlgebra.SingularException(2)

In [59]:
A = rand(1000, 1000); # Matriz "grande"

In [60]:
B = rand(1000);

In [61]:
@time A \ B;

  0.353999 seconds (361.85 k allocations: 20.903 MiB, 5.15% gc time)
